 # see https://symfony.com/doc/current/reference/configuration/framework.html
# config/packages/framework.yaml
framework:
    http_client:
        scoped_clients:
            # only requests matching scope will use these options
            # github:
            #     scope: 'https://api\.github\.com'
            #     headers:
            #         Accept: 'application/vnd.github.v3+json'
            #         auth_basic: '%env(USERNAME)%:%env(PASSWORD)%'
                # ...

            # using base_uri, relative URLs (e.g. request("GET", "/repos/symfony/symfony-docs"))
            # will default to these options
            github:
                base_uri: 'https://api.github.com'
                headers:
                    Accept: 'application/vnd.github.v3+json'
                    auth_basic: '%env(USERNAME)%:%env(PASSWORD)%'
                    #Authorization: 'token %env(GITHUB_API_TOKEN)%'
                
                    
                # ...
                
    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true
