index:
    path: /
    controller: App\Controller\DefaultController::index
github:
    path: /github
    controller: App\Controller\GithubController::index
storeToDatabases:
    path: /store
    controller: App\Controller\DatabasesController::index