index:
    path: /
    controller: App\Controller\DefaultController::index
github:
    path: /github
    controller: App\Controller\GithubController::index
master:
    path: /master
    controller: App\Controller\MasterController::index
slave:
    path: /slave
    controller: App\Controller\SlaveController::index